### ISSUE TITLE
Worlds

### ISSUE THREAD

**Issue by dirkson** [Bartkk0/VRCSDKonLinux#3]
A version for worlds might be useful too. I'd have done it as a pull request, but I couldn't work out how you generated the .dll diff files. For safety/maintainability, any chance we could get a quick breakdown of that process too?

**Comment by Bartkk0** [comment]
Oh, I was going to put the dll diff but I forgot about it, added it now in the readme. Might work on the world sdk later, but pull requests are welcome. ;-)

**Comment by Bartkk0** [comment]
Closing as worlds are supported now.
