### ISSUE TITLE
Current openbeta avatar SDK is broken? 

### ISSUE THREAD

**Issue by Naia-love** [Bartkk0/VRCSDKonLinux#6]
Hi, today I tried to use your script to script on the [open beta avatar sdk available on their discord server](https://canary.discord.com/channels/189511567539306508/503009489486872583/949426889557164132) (i have never tried using your script before btw):

But so first i get this when i run it
```
 ./patch.sh
Select SDK location: 
/home/naia/Unity/New Unity Project/Assets/VRCSDK
dos2unix: conversion du fichier Dependencies/VRChat/Editor/ControlPanel/VRCSdkControlPanelSettings.cs au format Unix…
dos2unix: conversion du fichier Dependencies/VRChat/Editor/ControlPanel/VRCSdkControlPanelAccount.cs au format Unix…
patching file Dependencies/VRChat/Editor/ControlPanel/VRCSdkControlPanelAccount.cs
patching file Dependencies/VRChat/Editor/ControlPanel/VRCSdkControlPanelSettings.cs
xdelta3: target window checksum mismatch: XD3_INVALID_INPUT
xdelta3: normally this indicates that the source file is incorrect
xdelta3: please verify the source file with sha1sum or equivalent
```
I have no idea if the xdelta3 error is expected or not, but that could be the reason why it don't seems to work, the DLL changed?  

In unity I can set my steamapp folder, which I do, but when I click build and test, it build and nothing else happen, note that I have always done avatars on linux without knowing this script before so I have no idea what it's even supposed to do, but when i lauch the game, I have nothing news in my avatars tabs etc

**Comment by japannt** [comment]
Can you try using the _stable_ sdk from the website?

**Comment by Bartkk0** [comment]
Probably the DLL changed between updates, you need to create patch manually with dnSpy, the source is in the GUIDPatch directory.

**Comment by Bartkk0** [comment]
Closing as the patcher was updated.
