### ISSUE TITLE
SDK3 world builds fail due to filename case

### ISSUE THREAD

**Issue by JillCrungus** [Bartkk0/VRCSDKonLinux#7]
In the latest worlds SDK version builds will fail inside `VRCWorldAssetExporter.ExportCurrentSceneResource` when the SDK attempts to copy/delete the world's VRCW file.

When the file is created, its name is made to be all lowercase, but this function doesn't account for that and as a result on case sensitive filesystems the build will fail.

**Comment by SpookySkeletons** [comment]
@JillCrungus Could use EXT4 case insensitive mounted image to bypass issue for now.

Can you confirm that an EXT4 loop image with case ins on solves world upload issues?

**Comment by Bartkk0** [comment]
Fixed with the new update
